import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { expect, type Page } from "@playwright/test";

/**
 * Reads one of the small checked-in fixtures. They are plain files rather than
 * generated bytes so a reviewer can see exactly what the signature validator is
 * being shown.
 */
export function fixtureBytes(name: string): Buffer {
  return readFileSync(resolve(process.cwd(), "tests", "e2e", "fixtures", name));
}

/** The row for one file, in either the personal library or a room section. */
export function resourceRow(page: Page, title: string) {
  return page.getByRole("listitem").filter({ hasText: title });
}

export type UploadTarget = { kind: "personal" } | { kind: "room"; roomId: string };

/**
 * Fills and submits one upload form through the real UI, returning as soon as
 * the request has been sent. The id prefix mirrors `ResourceLibrary`'s —
 * `personal` on `/resources`, `room-<uuid>` inside a workspace — so one helper
 * drives both surfaces.
 *
 * Callers await the row themselves when a rejection is the expected outcome;
 * awaiting success here would make a negative test time out instead of fail.
 */
export async function submitUploadViaUi(
  page: Page,
  target: UploadTarget,
  file: { name: string; mimeType?: string; buffer: Buffer },
  title: string,
  extras: { subject?: string; chapter?: string } = {},
): Promise<void> {
  const prefix = target.kind === "personal" ? "personal" : `room-${target.roomId}`;

  await page.locator(`#${prefix}-upload-file`).setInputFiles({
    name: file.name,
    mimeType: file.mimeType ?? "application/pdf",
    buffer: file.buffer,
  });
  await page.locator(`#${prefix}-upload-title`).fill(title);
  if (extras.subject !== undefined) {
    await page.locator(`#${prefix}-upload-subject`).fill(extras.subject);
  }
  if (extras.chapter !== undefined) {
    await page.locator(`#${prefix}-upload-chapter`).fill(extras.chapter);
  }

  await page.getByRole("button", { name: "Upload", exact: true }).click();
}

/** The same flow, resolved once the new row is on screen. */
export async function uploadViaUi(
  page: Page,
  target: UploadTarget,
  file: { name: string; mimeType?: string; buffer: Buffer },
  title: string,
  extras: { subject?: string; chapter?: string } = {},
): Promise<void> {
  await submitUploadViaUi(page, target, file, title, extras);
  await expect(resourceRow(page, title)).toBeVisible();
}

/** The heading of whichever library surface the page is showing. */
export function libraryHeading(page: Page, level: 1 | 2, name: string) {
  return page.getByRole("heading", { level, name });
}
